### ISSUE TITLE
why another plugin

### ISSUE THREAD

**Issue by tikismoke** [vdomos/domogik-plugin-onewired#1]
Why not working on this one:
https://github.com/Cereal2nd/domogik-plugin-onewire

**Comment by vdomos** [comment]
Celui de Cereal ne gère pas certains de mes chips 1-wire et le plugin fonctionne différement.
je ne lis que les attributs des sensors utlisés physiquement.Pas besoin de renvoyer la temperature d'un DS2438 par exemple si pas utlisée (d'ailleurs peu précise par rapport un DS18B20)

Autre point bloquant, le plugin de Cereal rencoie un sensor humidity pour le DS2438 alors que celui-ci est un CAN et peux donc renvoyer tout type de valeur. J'ai un ds2438 pour une girouette et un autre pour la luminosité du sous-sol par exemple.

Plus le fait d'utliser MQ au lieu de xPL.

**Comment by tikismoke** [comment]
ok
